---
### 1. The Creator & The History
Who: Travis Oliphant. When: 2005/2006.

The Context: Before NumPy, Python had two competing libraries for handling arrays: Numeric (created by Jim Hugunin) and Numarray. This split the community; code written for one didn't work with the other.

`Travis Oliphant`, a data scientist and professor, recognized that for Python to succeed in science, it needed one unified, high-performance array package. He took the best parts of Numeric, rewrote the core to be more flexible (borrowing from Numarray), and released it as NumPy (Numeric Python).

2. The First Principle Problem: "The Boxed Integer"
Why did we need NumPy? Why wasn't standard Python good enough?

The answer lies in Memory Overhead and CPU Cycles.

The Problem with Python Lists
In standard Python, everything is an object. When you create a list x = [1, 2, 3], the computer does not just store the numbers 1, 2, 3 next to each other.

Pointer Chase: The list x contains pointers (addresses).

The Box: Each pointer points to a separate Python Object (a "box") scattered in memory.

The Overhead: Inside that box is the actual number, plus metadata (reference count, type info).

Because the data is scattered (non-contiguous), the CPU cannot predict what data comes next, leading to "cache misses," which makes processing very slow.

The Problem with Python Loops
If you want to add two lists element-by-element in pure Python:

Python

### Pure Python
```python
c = []
for i in range(len(a)):
    c.append(a[i] + b[i])

# For every single number, Python has to:
# 1. Check the type of a[i] (Is it an int?).
# 2. Check the type of b[i].
```

Unbox the numbers.

Add them.

Box the result back into a Python object.

This is incredibly inefficient for millions of numbers.

3. The Solution: Contiguous Memory & Vectorization
NumPy solved this by going back to the first principles of C-style memory management.

Solution A: Contiguous Memory
A NumPy array is a solid block of memory. It stores the raw binary data (e.g., 010101) right next to each other.

No Pointers: It doesn't store pointers to objects; it stores the values themselves.

Homogeneity: It forces all data to be the same type (e.g., int64). Because the type is known upfront, NumPy doesn't need to check the type of every single element.

Solution B: Vectorization (SIMD)
Because the memory is contiguous and the types are known, NumPy can use SIMD (Single Instruction, Multiple Data) instructions.

Instead of adding numbers one by one, the CPU can load a block of 4 or 8 numbers at once and add them in a single clock cycle. This is called Vectorization.

The Result: NumPy operations are often 50x to 100x faster than Python lists

---
- ### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences ( eg list , tuple , dict ,set )

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## NOTES --->> The argument to np.array() should be one single sequence (like a list, or a list of lists).

### Creating Numpy Arrays

In [ ]:
# np.array

import numpy as np 

a = np.array ( [1, 2, 3] )
print (a)
print( type ( a))

# [1 2 3]
# <class 'numpy.ndarray'>


[1 2 3]
<class 'numpy.ndarray'>


- ## numpy.array(object, dtype=None, ...)
- ### only one object at a time

1. The Principle of Positional Arguments
In Python, if you don't specify argument names (like dtype=...), arguments are assigned based on their position.

```python
def array(object, dtype=None, ...):
    # internal logic
```

- When you wrote:np.array([1,2,3], [4,5,6])

- Python assigned your inputs strictly by order:

- Argument 1 (object) $\rightarrow$ [1, 2, 3]

- Argument 2 (dtype) $\rightarrow$ [4, 5, 6]

- The Mistake: You intended [4, 5, 6] to be part of the data, but NumPy thinks it is a data type definition.



In [ ]:
import numpy as np 

b = np.array(
              [1,2,3],
              [4,5,6]
            )

# TypeError: Field elements must be 2- or 3-tuples, got '4'

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [5]:
# 2D and 3D

b = np.array(
    [ [1,2,3],
      [4,5,6] ] )
print(b) 
print(type (b) )

print ( b.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [3]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr)
print("Shape:", arr.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


## NOTES -->> 
- 👉 So, a 3×3 array with 9 elements is always 2D, not 3D.
- 3D arrays would need multiple 3×3 blocks stacked.

In [6]:
c = np.array(
    [[ [1,2],
      [3,4]],
     [[5,6],[7,8] ]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


---
- ### Correct. A $3 \times 3$ grid is like a single sheet of paper with a grid drawn on it. It has Height (Rows) and Width (Columns).
- ### It does not have Depth. To make it 3D, you would need to stack multiple $3 \times 3$ sheets on top of one another

SyntaxError: invalid syntax (1948120211.py, line 1)

In [7]:
import numpy as np

arr = np.array([
    [  # block 1
        [1, 2],
        [3, 4]
    ],
    [  # block 2
        [5, 6],
        [7, 8]
    ]
])

print(arr)
print("Shape:", arr.shape)
print(arr.ndim)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
3


### NOTES -->> 
- dtype stands for data type in NumPy.

- It tells NumPy what type of data should be stored in the array.

- By default, NumPy tries to guess the type from the input values.

- But when you specify dtype, you are forcing NumPy to store the array elements in the data type you want.

In [8]:
# dtype
np.array( [1,2,3],  dtype=float )

array([1., 2., 3.])

In [9]:
# dtype of bool 
np.array([1,2,3],dtype= bool )

# in python Non zero number is considered as True
# array([ True,  True,  True])



array([ True,  True,  True])

In [10]:
# dtype of complex 
np.array( [1,2,3],  dtype= complex  )


array([1.+0.j, 2.+0.j, 3.+0.j])

### NOTES -->> 
- np.arange(1, 11) → creates numbers from 1 to 10.

- .reshape(5, 2) → reorganizes those numbers into a 5×2 matrix.

In [11]:
# np.arange similar to loop of range 
np.arange(1,11 , 2 )


array([1, 3, 5, 7, 9])

In [12]:
# np.arange similar to loop of range 
np.arange(1,11 ).reshape ( 5 , 2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
# np.arange similar to loop of range 
np.arange(1,11 ).reshape ( 2, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
# with reshape
np.arange(16).reshape(2,2,2,2)


# array(
# [
#     [
#         [[ 0,  1],
#          [ 2,  3]],

#         [[ 4,  5],
#          [ 6,  7]]
#     ],

#     [
#         [[ 8,  9],
#          [10, 11]],

#         [[12, 13],
#          [14, 15]]
#     ]
# ]
# )



array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [15]:
# np.ones and np.zeros  -->> uses of this in the filed of initializing the node of nural networks 
np.ones( (3,4) )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
# np.ones and np.zeros  -->> uses of this in the filed of initializing the node of nural networks 
np.ones( (3 ,4, 3  ) )

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [66]:
zero1 = np.zeros((3,4))
print (zero1)
print ( type(zero1) )
print ( zero1.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
(3, 4)


In [18]:
# np.random
np.random.random((3,4))

array([[0.3894329 , 0.2804866 , 0.00853435, 0.25535423],
       [0.44487457, 0.34358112, 0.64446059, 0.7983779 ],
       [0.18421424, 0.92578792, 0.14678789, 0.4633999 ]])

In [19]:
# np.linspace -->> Linearly or linear space 

# linspace ( lower rage , upper range , how much no)

np.linspace(-10,10,10,dtype=int)


array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [20]:
# np.identity
np.identity(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
# np.identity
np.identity(6) 

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Array Attributes

In [5]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
# ndim  -->> types of array 2D, 3D, 4D array
a3.ndim

3

In [70]:
# shape
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [23]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
# size  -->> how may no of elements in the array
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

---
- 8 bits = 1 byte.
- $32 \div 8 = 4$ bytes.

| Data Type | Bits | Calculation | itemsize (Bytes) |
| :--- | :--- | :--- | :--- |
| `int8` | 8 bits | $8/8$ | **1** |
| `int16` | 16 bits | $16/8$ | **2** |
| `float32` | 32 bits | $32/8$ | **4** |
| `float64` / `int64` | 64 bits | $64/8$ | **8** |

In [7]:
# itemsize -->> how many memory occupied by each element of arry 
# a3.itemsize tells you the size of one single element in bytes.


a3.itemsize

8

In [26]:
# itemsize
a1.itemsize

4

In [27]:
# itemsize
a2.itemsize

8

In [3]:
import numpy as np

arr = np.array([10, 20, 30])
print(arr.dtype)  
# Output: int64 
# Meaning: "Every single item in this list is a 64-bit integer."

int64


In [4]:
print(type(arr)) 
# Output: <class 'numpy.ndarray'>
# Meaning: "This object is a NumPy N-Dimensional Array."

<class 'numpy.ndarray'>


In [28]:
# dtype
print(a1.dtype)
print(a2.dtype )
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [74]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [75]:
# astype
print ( a3)
print ( type( a3))
print(a3.dtype)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
<class 'numpy.ndarray'>
int64


In [29]:
# astype

# print(a3.dtype) #int64

a3.astype(np.int32)
 
  

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [77]:
# astype

# print(a3.dtype) #int64

a3.astype(np.int8)
 
  

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int8)

In [76]:
print(a3.dtype)
 

int64


### Array Operations

In [30]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

---
- ## `a2.reshape(-1) ` multi-array into 1D array

In [20]:
a2.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [33]:
a1 > 5 

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

##  vector operations


In [35]:
# vector operations
# arithmetic for all operaters + , - , / // * 
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [36]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[34., 96., 75.],
       [11., 13., 65.],
       [60., 35., 31.]])

In [37]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1)

np.float64(96.0)

In [38]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1 , axis=0)

array([60., 96., 75.])

In [39]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.sum(a1 )

np.float64(420.0)

In [40]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.sum(a1 , axis=0)

array([105., 144., 171.])

In [41]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.min(a1 , axis=0)

array([11., 13., 31.])

In [42]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([ 22440.,  43680., 151125.])

In [43]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0) 

array([ 22440.,  43680., 151125.])

##  mean/median/std/var


In [44]:
# mean/median/std/var
np.mean(a1,axis=1)

array([68.33333333, 29.66666667, 42.        ])

In [45]:
# mean/median/std/var
np.median(a1,axis=1)

array([75., 13., 35.])

In [46]:
# mean/median/std/var
np.std(a1)

np.float64(27.280436620813497)

In [47]:
# mean/median/std/var
np.var(a1,axis=1)

array([662.88888889, 624.88888889, 164.66666667])

--- 
## trigonomoetric functions
### sin , cos, sec ,tan


In [48]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.52908269,  0.98358775, -0.38778164],
       [-0.99999021,  0.42016704,  0.82682868],
       [-0.30481062, -0.42818267, -0.40403765]])

In [49]:
# trigonomoetric functions
np.cos(a1 , axis=1 )

TypeError: cos() got an unexpected keyword argument 'axis'

In [ ]:
# trigonomoetric functions
np.cos(a1)

In [ ]:
# trigonomoetric functions
np.tan(a1)

In [ ]:
# trigonomoetric functions
np.sin(a1)

##  `dot product`
 It should flow the matrix multiplication rule 
 3 * 4  X 4 * 5 

In [ ]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

In [ ]:
# log and exponents

np.exp(a1)


In [ ]:
# log and exponents

np.log(a1)


## round/floor/ceil


In [8]:
# round/floor/ceil

np.random.random((2,3))*100

array([[83.99074436, 51.15058266, 89.05332578],
       [98.26484933, 39.09201585, 92.26923087]])

In [9]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[79., 77., 55.],
       [ 1., 90., 53.]])

In [10]:
# round/floor/ceil

np.floor(np.random.random((2,3))*100)

array([[39.,  5., 69.],
       [ 5., 14., 80.]])

In [11]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[94., 43., 63.],
       [37., 11., 73.]])

### Indexing and Slicing

In [12]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

In [ ]:
a1[-1]

In [ ]:
a1[0]

In [14]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a2[1][2]

np.int64(6)

In [15]:
a2[1,2]

np.int64(6)

In [16]:
a2[1,0]

np.int64(4)

In [ ]:
a3

In [ ]:
a3[1,0,1] 

In [ ]:
a3[0,1,0] 

In [ ]:
a3[1,1,0]

### slicing 

In [ ]:
a1


In [ ]:
a1[2:5]

In [ ]:
a1[2:5:2]

In [ ]:
a2

In [ ]:
a2[0]

In [ ]:
a2[0 , :]

In [ ]:
a2[ : , 2]

In [ ]:
a2[0:2]

In [ ]:
a2

In [ ]:
a2[  1: ,1:3] 

In [ ]:
a2[0:2,1::2]

In [ ]:
a2[::2,1::2]

In [ ]:
a2[1,::3]

In [ ]:
a2[0,:]

In [ ]:
a2[:,2]

In [ ]:
a2[1:,1:3]

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

In [ ]:
a3[::2,0,::2]

In [ ]:
a3[2,1:,1:]

In [ ]:
a3[0,1,:]

### Iterating

In [ ]:
import numpy as np 

a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
a1

In [ ]:
a2

In [ ]:
a3

In [ ]:
a1

for i in a1:
  print(i)

In [ ]:
a2

In [ ]:
for i in a2:
  print(i)

#@ NOTES -->>  Its printing one row at a time in array of matrix in 2D in operation Loop

In [ ]:
a3

In [ ]:
for i in a3:
  print(i)
## NOTES -->  in 3D in array  one 2D array will printed

In [ ]:
for i in np.nditer(a3):
  print(i)

### Reshaping

In [ ]:
# reshape

In [ ]:
a2

In [ ]:
# Transpose
np.transpose(a2)
a2.T

In [ ]:
a3

In [ ]:
# ravel
a3.ravel()

### Stacking

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

In [ ]:
np.hstack((a4,a5))

In [ ]:
# Vertical stacking
np.vstack((a4,a5))

### Splitting

In [ ]:
# horizontal splitting
a4

In [ ]:
np.hsplit(a4,5)

In [ ]:
# vertical splitting

In [ ]:
a5

In [ ]:
np.vsplit(a5,2)